<?php
/* $Id$ */

/**
 * @file
 * Very simple DRUPAL module
 */

/**
 * Implementation of hook_menu().
 */
function moduloprueba2_menu($may_cache) {
  $items = array();

  $items['holamundo'] = array(
    'title' => 'Hola mundoooo!',
    'access callback' => TRUE,
    'page callback' => 'moduloprueba2_hello_world_page',
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  );

  return $items;
}


/**
 * Function which generate page
 */
function moduloprueba2_hello_world_page() {
  return '<p>Hola mundo prueba 2!</p>';
}